"""Create Plane

Revision ID: 27d811817dc4
Revises:
Create Date: 2025-12-18 13:21:36.428432

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "27d811817dc4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "planes",
        sa.Column("type_plane", sa.String(length=10), nullable=False),
        sa.Column("serial_number", sa.String(length=32), nullable=False),
        sa.Column("tail_number", sa.String(length=32), nullable=False),
        sa.Column("base_airfield", sa.String(length=100), nullable=False),
        sa.Column("belong_plane", sa.String(length=100), nullable=False),
        sa.Column("operating_time", sa.Integer(), nullable=False),
        sa.Column("manufacturer_date", sa.Date(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("serial_number"),
        sa.UniqueConstraint("tail_number"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("planes")
    # ### end Alembic commands ###
